server {
    listen 80 default_server;
    server_name _;

    client_max_body_size 20M;

    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }

    location ~ \.php(?:/|$) {
        return 404;
    }

    location / {
        include fastcgi_params;
        fastcgi_pass platform-service-php:9000;

        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/html/public;

        fastcgi_param PHP_VALUE "upload_max_filesize=20M \n post_max_size=20M";

        fastcgi_read_timeout 300s;
        fastcgi_buffer_size 128k;
        fastcgi_buffers 4 256k;
        fastcgi_busy_buffers_size 256k;
    }
}