upstream php-fpm {
    server platform-service-php:9000;
    keepalive 16;
}

server {
    listen 80 default_server;
    server_name _;
    

    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }

    location ~ \.php(?:/|$) {
        return 404;
    }

    location = /health {
        access_log off;
        include conf.d/php-fastcgi.conf;
    }

    location = /api/v1/health {
        access_log off;
        include conf.d/php-fastcgi.conf;
    }

    location / {
        include conf.d/php-fastcgi.conf;
    }
}