include fastcgi_params;

fastcgi_pass php-fpm;

fastcgi_hide_header X-Powered-By;

fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
fastcgi_param SCRIPT_NAME /index.php;
fastcgi_param DOCUMENT_ROOT /var/www/html/public;

fastcgi_connect_timeout 3s;
fastcgi_send_timeout 15s;
fastcgi_read_timeout 30s;

fastcgi_buffer_size 16k;
fastcgi_buffers 8 16k;
fastcgi_busy_buffers_size 32k;

fastcgi_keep_conn on;